### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by XxsjrapsxX** [HimikoToga1474/Ahegao-Hub#1]
Recently if you attempt to leave the auto farm on all night you will get a prompt saying you are banned, but you can join back into the game. It may add you to a list of hackers to be banned. Please attempt to make this auto farm safer so that we dont have to worry about getting banned please.

**Comment by HimikoToga1474** [comment]
I would appreciate it if you would be a bit more specific. And maybe message me on discord instead, because I don't look at github often.

**Comment by XxsjrapsxX** [comment]
no need to worry this game is probably never getting updated again dog

**Comment by ThisKo0** [comment]
Before it reaches 30 days ago or a month ago, I would like to say goodbye to this beautiful script. Thank you, Himiko!

**Comment by ThisKo0** [comment]
> no need to worry this game is probably never getting updated again dog

awwww. Well, too bad they keep updating it.
